// This file is automatically generated. Do not edit it directly.
// (Extensão: header x-empresa-token para RLS via PostgREST - tokens de funcionário)
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Token da empresa quando funcionário autentica via token (RLS via header PostgREST)
let empresaToken: string | null = null;

const customFetch: typeof fetch = (input, init) => {
  const headers = new Headers(init?.headers || {});
  if (empresaToken) headers.set("x-empresa-token", empresaToken);
  return fetch(input, { ...init, headers });
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: { fetch: customFetch as any },
});

// Seta globalmente o token do funcionário para todas as queries subsequentes.
// Passar null/undefined para limpar (logout do funcionário / dono auth).
export function setEmpresaToken(token: string | null): void {
  empresaToken = token ?? null;
}
